### ISSUE TITLE
Identifier 'Sequelize' has already been declared

### ISSUE THREAD

**Issue by henning-oden** [henning-oden/nodejs-course#1]
Crash on app launch in test:

```
00-mvc\models\cart.js:2
const Sequelize = require('sequelize');
      ^

SyntaxError: Identifier 'Sequelize' has already been declared
    at wrapSafe (internal/modules/cjs/loader.js:992:16)
    at Module._compile (internal/modules/cjs/loader.js:1040:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (00-mvc\controllers\shop.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
```

**Comment by halaq** [comment]
Hi @henning-oden 
it says: `Identifier 'Sequelize' has already been declared`
just change the name, make it `seq` for example and check.

**Comment by henning-oden** [comment]
It turns out I had a duplicate line with a Sequelize declaration in cart.js that I at first did not see and that was not picked up when I was trying to compare code by creating #2 , however, this is now fixed. Thank you!
