### ISSUE TITLE
181. Finishing the Database Connection: Type Error: mongoConnect is not a function

### ISSUE THREAD

**Issue by henning-oden** [henning-oden/nodejs-course#4]
In trying to complete Lecture 181 I get an unexpected error:

```
TypeError: mongoConnect is not a function
    at Object.<anonymous> (F:\Documents\Node Course\00-mvc\app.js:34:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
The file with the contents of database.js can be found here: [database-js.txt](https://github.com/henning-oden/nodejs-course/files/5459915/database-js.txt) Other than that, all code is available as per commit https://github.com/henning-oden/nodejs-course/commit/c454efbe2652ec1779369533b4c8ef7ae944a8c3

**Comment by henning-oden** [comment]
Fixed in Lecture 182.
